name: Release Build
on: 
  push:
    branches: [ qa, ftqa, production ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
        
    - name: prepare for build
      run: npm install && npm update 
    
    - name: test
      run: npm run test
    
    - name: build
      id: run_build
      run: npm run github-build

    - name: commit
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit files for build ${{ steps.run_build.outputs.buildName }}"
        add: "package*.json dist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.run_build.outputs.buildName }}
        release_name: Release ${{ steps.run_build.outputs.buildName }}
        draft: false
        prerelease: true
        
    - name: set token
      run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} >  $HOME/.npmrc 2> /dev/null
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    - name: publish
      run: npm publish --tag ${{ steps.run_build.outputs.npmTag }}
     
